### ISSUE TITLE
TESS passband

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2-tables#3]
Add support for TESS passband?  PTF is available here: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse&gname=TESS

**Comment by aprsa** [comment]
Sure. I'll get to it this week.

**Comment by kecnry** [comment]
We also have a request for Spitzer (for PHOEBE 1, but might as well generate them for both I'm assuming).
